add 'Passed Lua tests' step

diff --git a/.github/workflows/build-mudlet-win.yml b/.github/workflows/build-mudlet-win.yml
--- a/.github/workflows/build-mudlet-win.yml
+++ b/.github/workflows/build-mudlet-win.yml
@@ -81,6 +81,14 @@ jobs:
         QUIT_MUDLET_AFTER_TESTS: 'true'
       run: $GITHUB_WORKSPACE/build-$MSYSTEM/release/mudlet.exe --profile "Mudlet self-test" --mirror
 
+    - name: Passed Lua tests
+      run: |
+        if [ -e /c/Users/$USER/busted-tests-failed ]
+        then
+          echo "Lua tests failed - see the action called 'Run Lua tests' above for detailed output."
+          exit 1
+        fi
+
     - name: Save ccache
       if: always() && steps.restore-ccache.outputs.cache-hit != 'true'
       uses: actions/cache/save@v4
